import { BookOpen, Check, Flame, Layers3, Play, RotateCcw, Sparkles } from "lucide-react";
import { useState } from "react";
import { type AppConfig, type ProfileState } from "../../../shared/study";

type Props = { profile: ProfileState; config: AppConfig; onView: (view: "flashcards" | "quizzes" | "plans") => void; onProfile: (profile: ProfileState, message?: string) => void };

export default function FocusHub({ profile, config: _config, onView, onProfile }: Props) {
  const [miniStarted, setMiniStarted] = useState(false);
  const [miniStep, setMiniStep] = useState(0);
  const miniSteps = [{ label: "5–10 Flashcard", view: "flashcards" as const }, { label: "1–3 câu trắc nghiệm", view: "quizzes" as const }, { label: "1 câu đúng/sai", view: "quizzes" as const }, { label: "1 câu trả lời ngắn", view: "quizzes" as const }];
  const weakSets = profile.flashcardSets.flatMap((set) => {
    const uncertain = set.cards.filter((card) => card.status !== "known");
    return uncertain.length ? [{ set, count: uncertain.length, certainty: Math.round((set.cards.length - uncertain.length) / Math.max(1, set.cards.length) * 100) }] : [];
  }).sort((a, b) => a.certainty - b.certainty).slice(0, 6);
  const planItems = profile.studyPlanItems ?? [];
  const dailyPlans = planItems.filter((item) => item.cadence === "day");
  const weeklyPlans = planItems.filter((item) => item.cadence === "week");
  const pendingPlans = planItems.filter((item) => !item.completedAt);
  const encouragement = ["Hôm nay chỉ cần tiến thêm một chút thôi.", "Không cần hoàn hảo. Chỉ cần bắt đầu.", "Ong quay lại rồi, mình học một chút nhé."][new Date().getDate() % 3];
  return <div className="space-y-6">
    <section className="rounded-3xl bg-gradient-to-br from-[#8d5d15] via-amber-500 to-yellow-400 p-6 text-white shadow-xl shadow-amber-500/20"><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-100">Ong hôm nay thế nào?</p><h1 className="mt-2 font-display text-3xl font-bold">{encouragement}</h1><div className="mt-5 flex flex-wrap items-center gap-3"><button className="rounded-xl bg-white px-4 py-3 text-sm font-bold text-amber-900" onClick={() => { setMiniStarted(true); setMiniStep(0); }}><Play className="mr-2 inline h-4 w-4" />Học 10 phút</button><span className="rounded-xl bg-white/15 px-4 py-3 text-sm font-bold"><Flame className="mr-2 inline h-4 w-4" />{profile.studyActivity.length} hoạt động học đã lưu</span></div></section>
    <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <section className="panel p-6" aria-labelledby="smart-review-title"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-700 dark:text-amber-300">Ôn lại thông minh</p><h2 id="smart-review-title" className="mt-2 font-display text-2xl font-bold">Những phần Ong chưa chắc</h2><p className="mt-2 text-sm leading-6 text-slate-500">Ưu tiên thẻ mới và thẻ chưa nhớ thay vì học lại toàn bộ.</p></div><RotateCcw className="h-6 w-6 text-amber-600" /></div>{weakSets.length ? <div className="mt-5 space-y-3">{weakSets.map(({ set, count, certainty }) => <div key={set.id} className="flex items-center gap-3 rounded-2xl border border-amber-100 p-3 dark:border-amber-400/15"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-amber-100 text-amber-800 dark:bg-amber-500/15 dark:text-amber-200"><BookOpen className="h-4 w-4" /></div><div className="min-w-0 flex-1"><b className="block truncate text-sm">{set.subject} · {set.topic || set.title}</b><span className="text-xs text-slate-500">{count} thẻ cần ôn · Độ chắc chắn {certainty}%</span></div><button className="secondary-button px-3 py-2 text-xs" onClick={() => onView("flashcards")}>Ôn ngay</button></div>)}</div> : <p className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900 dark:bg-amber-500/10 dark:text-amber-100">Chưa có phần yếu rõ ràng. Hãy học một bộ mới để hệ thống bắt đầu theo dõi.</p>}</section>
      <section className="panel p-6" aria-labelledby="plan-overview-title"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-700 dark:text-amber-300">Kế hoạch tự quản lý</p><h2 id="plan-overview-title" className="mt-2 font-display text-2xl font-bold">Việc học đang chờ</h2></div><Layers3 className="h-6 w-6 text-amber-600" /></div><p className="mt-2 text-sm text-slate-500">Còn {pendingPlans.length} mục: {dailyPlans.filter((item) => !item.completedAt).length} theo ngày và {weeklyPlans.filter((item) => !item.completedAt).length} theo tuần.</p><div className="mt-5"><div className="rounded-2xl bg-amber-50 p-4 dark:bg-amber-500/10"><b className="block text-sm">Mảnh ghép Kế hoạch</b><span className="mt-1 block text-2xl font-bold">{profile.planFragments}</span></div></div><button className="secondary-button mt-5 px-4 py-2 text-sm" onClick={() => onView("plans")}>Mở Kế hoạch</button></section>
    </div>
    <section className="panel p-6"><div className="flex items-start gap-3"><Sparkles className="mt-1 h-5 w-5 text-amber-600" /><div className="min-w-0 flex-1"><h2 className="font-display text-xl font-bold">Cấu trúc một phiên 10 phút</h2><p className="mt-2 text-sm leading-6 text-slate-500">Một mini-session có mục tiêu nhỏ, đủ để duy trì nhịp học mà không tạo áp lực.</p>{miniStarted && <div className="mt-5 space-y-2" role="list" aria-label="Các chặng trong phiên học 10 phút">{miniSteps.map((step, index) => <div key={step.label} className="flex items-center gap-3 rounded-xl border border-amber-100 p-3 dark:border-amber-400/15"><span className={`grid h-7 w-7 place-items-center rounded-full text-xs font-bold ${index < miniStep ? "bg-amber-500 text-white" : "bg-amber-50 text-amber-800 dark:bg-amber-500/10 dark:text-amber-200"}`}>{index < miniStep ? <Check className="h-4 w-4" /> : index + 1}</span><span className="flex-1 text-sm font-bold">{step.label}</span>{index === miniStep && <button className="secondary-button px-3 py-2 text-xs" onClick={() => { onView(step.view); const nextStep = Math.min(miniSteps.length, miniStep + 1); setMiniStep(nextStep); if (nextStep === miniSteps.length) { const occurredAt = new Date().toISOString(); onProfile({ ...profile, lastActivityAt: occurredAt, studyActivity: [{ id: `mini-${occurredAt}`, occurredAt, kind: "flashcard", quantity: 1, durationSeconds: 600, xpEarned: 0 }, ...profile.studyActivity] }, "Đã ghi nhận phiên Học 10 phút trong lịch sử học."); } }}>{index === 0 ? "Bắt đầu" : "Mở"}</button>}</div>)}</div>}</div></div></section>
  </div>;
}
