import type { ProfileState } from "../../../shared/study";

const formatTime = (value: string) => new Date(value).toLocaleString("vi-VN", { dateStyle: "medium", timeStyle: "short" });

export default function StudyHistory({ profile }: { profile: ProfileState }) {
  const pomodoroSessions = [...profile.pomodoroHistory].filter((item) => item.mode === "focus").sort((a, b) => new Date(b.endedAt).getTime() - new Date(a.endedAt).getTime());
  const rows = profile.flashcardSets.map((set) => { const related = profile.studyActivity.filter((item) => item.kind === "flashcard" && item.id.includes(set.id)); const attempts = profile.attempts.filter((attempt) => attempt.quizId === set.id); const scores = attempts.map((attempt) => attempt.accuracy); return { id: set.id, name: set.title, source: set.topic || set.subject, cards: set.cards.length, sessions: Math.max(set.studyCount, related.length), best: scores.length ? Math.max(...scores) : null, average: scores.length ? Math.round(scores.reduce((sum, score) => sum + score, 0) / scores.length) : null, weak: set.cards.filter((card) => card.status !== "known").length }; });
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-700 dark:text-amber-300">Lịch sử học</p><h1 className="mt-2 font-display text-4xl font-bold">Những gì bạn đã thực hiện</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500 dark:text-slate-300">Lịch sử lưu theo hồ sơ riêng: các phiên Pomodoro có ngữ cảnh, bộ Flashcard đã ôn và đề đã làm. Mục Kế hoạch chỉ được ghi là ngữ cảnh, không tự đánh dấu hoàn thành thay bạn.</p></div>
    <section className="panel p-5 sm:p-6" aria-labelledby="pomodoro-history-title"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-700 dark:text-emerald-300">Phiên tập trung</p><h2 id="pomodoro-history-title" className="mt-1 font-display text-2xl font-black">Pomodoro đã lưu</h2></div><strong className="rounded-full bg-emerald-50 px-3 py-1 text-sm text-emerald-900 dark:bg-emerald-400/10 dark:text-emerald-100">{pomodoroSessions.length} phiên</strong></div>{pomodoroSessions.length ? <div className="mt-5 space-y-3">{pomodoroSessions.map((session) => <article className="rounded-2xl border border-emerald-100 bg-emerald-50/40 p-4 dark:border-emerald-300/15 dark:bg-emerald-400/5" key={session.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold text-slate-950 dark:text-white">{session.subject || "Tự học"} <span className="font-normal text-slate-500">· {session.topic || "Chưa ghi nội dung"}</span></h3><p className="mt-1 text-xs font-semibold text-slate-500">{formatTime(session.endedAt)} · {session.durationMinutes} phút · {session.activity || "Học tập"}</p></div><span className="rounded-full bg-white px-2.5 py-1 text-xs font-black text-emerald-800 dark:bg-slate-900 dark:text-emerald-200">Đã lưu</span></div>{session.checkedPlanTitles?.length ? <div className="mt-3"><p className="text-xs font-bold text-slate-500">Công việc đã chọn trong phiên</p><div className="mt-2 flex flex-wrap gap-2">{session.checkedPlanTitles.map((title) => <span className="rounded-full border border-emerald-200 bg-white px-2.5 py-1 text-xs font-semibold text-emerald-900 dark:border-emerald-300/20 dark:bg-slate-900 dark:text-emerald-100" key={title}>✓ {title}</span>)}</div></div> : null}{session.notes ? <blockquote className="mt-3 border-l-2 border-emerald-400 pl-3 text-sm leading-6 text-slate-600 dark:text-slate-200">{session.notes}</blockquote> : null}</article>)}</div> : <p className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm text-slate-500 dark:bg-white/5">Chưa có phiên Pomodoro hoàn thành. Khi kết thúc một phiên, môn học, nội dung, công việc đã chọn và ghi chú sẽ hiện tại đây.</p>}</section>
    <section><div className="mb-3"><p className="text-xs font-black uppercase tracking-[.16em] text-amber-700 dark:text-amber-300">Flashcard và đề</p><h2 className="mt-1 font-display text-2xl font-black">Nguồn học đã tạo</h2></div>{rows.length ? <div className="grid gap-4 md:grid-cols-2">{rows.map((row) => <article className="panel p-5" key={row.id}><div className="flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-amber-50 text-amber-800 dark:bg-amber-500/10 dark:text-amber-200">📚</span><div><h3 className="font-display text-xl font-bold">{row.name}</h3><p className="text-sm text-slate-500">Nguồn/chủ đề: {row.source || "Chưa gắn chủ đề"}</p></div></div><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-slate-500">Flashcard</dt><dd className="font-bold">{row.cards}</dd></div><div><dt className="text-slate-500">Lần ôn</dt><dd className="font-bold">{row.sessions}</dd></div><div><dt className="text-slate-500">Điểm cao nhất</dt><dd className="font-bold">{row.best == null ? "—" : `${row.best}%`}</dd></div><div><dt className="text-slate-500">Điểm trung bình</dt><dd className="font-bold">{row.average == null ? "—" : `${row.average}%`}</dd></div></dl><p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-900 dark:bg-amber-500/10 dark:text-amber-100">{row.weak} thẻ chưa ở trạng thái chắc</p></article>)}</div> : <div className="panel grid min-h-36 place-items-center p-8 text-center"><p className="text-sm text-slate-500">Khi tạo và ôn Flashcard, dữ liệu nguồn học sẽ hiện tại đây.</p></div>}</section></div>;
}
