import fs from "node:fs";
const path = "client/src/components/ExperienceStudio.tsx";
const source = fs.readFileSync(path, "utf8");
const start = source.indexOf('    {profile && onProfile ? <PersistentCollapsible storageKey="experience-lumi-favorite-scenes"');
const end = source.indexOf('    <PersistentCollapsible storageKey="experience-emotion-command"', start);
if (start < 0 || end < 0) throw new Error("favorite panel boundaries not found");
const replacement = `    {profile && onProfile ? <PersistentCollapsible storageKey="experience-lumi-favorite-scenes" eyebrow="Giao diện của Lumi" title="Giao diện yêu thích" className="relative z-10 mt-4 border-amber-200 bg-amber-50/80"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-amber-800">Giao diện yêu thích</p><p className="mt-1 text-xs text-amber-900/75">Danh sách không giới hạn. Nhấn một theme để áp dụng, bấm sao để thêm hoặc bỏ.</p></div><Star className="h-5 w-5 fill-amber-400 text-amber-500" aria-hidden="true" /></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5">{sceneOptions.map((scene) => { const isFavorite = (profile.favoriteAmbientScenes ?? []).includes(scene.id); return <div key={scene.id} className={\`rounded-xl border p-2 transition \${ambientScene === scene.id ? "border-amber-500 bg-white shadow-sm" : "border-amber-200 bg-white/70"}\`}><div className="flex items-center justify-between gap-1"><button type="button" aria-pressed={ambientScene === scene.id} onClick={() => setScene(scene.id)} className="min-w-0 flex-1 truncate text-left text-xs font-black text-amber-950">{scene.label}</button><button type="button" aria-label={\`\${isFavorite ? "Bỏ" : "Thêm"} yêu thích \${scene.label}\`} onClick={() => toggleFavoriteAmbientScene(scene.id)} className="rounded-md p-1 hover:bg-amber-100"><Star className={\`h-3.5 w-3.5 \${isFavorite ? "fill-amber-400 text-amber-500" : "text-amber-400"}\`} /></button></div><p className="mt-1 text-[10px] text-amber-900/70">{isFavorite ? "Đã yêu thích" : "Bấm sao để lưu"}</p></div>; })}</div></PersistentCollapsible> : null}
`;
fs.writeFileSync(path, source.slice(0, start) + replacement + source.slice(end));
console.log("favorite panel replaced");
