import { useMemo, useState } from "react";
import { achievementTopics, emptyProfile, allAchievementsWithProgress, type Achievement, type AppConfig } from "../../../shared/study";

type Props = { config: AppConfig };

const statusLabel = (item: Achievement) => item.enabled === false ? "Tạm ẩn" : item.unlockedAt ? "Đã đạt" : "Chưa đạt";

export default function AchievementCatalogAdmin({ config }: Props) {
  const [query, setQuery] = useState("");
  const [level, setLevel] = useState("all");
  const [topic, setTopic] = useState("all");
  const [status, setStatus] = useState("all");
  const [kind, setKind] = useState<"all" | "achievement" | "title">("all");
  const [selected, setSelected] = useState<Achievement | null>(null);
  const catalog = useMemo(() => allAchievementsWithProgress(emptyProfile(), config).filter((item) => item.achievementCode.startsWith("ACH-")), [config]);
  const filtered = useMemo(() => catalog.filter((item) => {
    const text = `${item.name} ${item.achievementCode} ${item.description}`.toLowerCase();
    return (!query.trim() || text.includes(query.trim().toLowerCase())) &&
      (level === "all" || item.level === Number(level)) &&
      (topic === "all" || item.topic === topic) &&
      (status === "all" || statusLabel(item) === status) &&
      (kind === "all" || (kind === "title" ? Boolean(item.title) : !item.title));
  }), [catalog, query, level, topic, status, kind]);
  const titles = filtered.filter((item) => Boolean(item.title));
  const reset = () => { setQuery(""); setLevel("all"); setTopic("all"); setStatus("all"); setKind("all"); };
  return <section className="panel mt-7 p-5" aria-labelledby="achievement-admin-catalog-title">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-red-700 dark:text-red-300">CATALOG CÔNG KHAI</p><h2 id="achievement-admin-catalog-title" className="mt-1 font-display text-2xl font-bold">Quản lý 900 Thành tích · 400 Danh hiệu</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Toàn bộ catalog được hiển thị từ đầu. Bảng này dùng để tìm, lọc, xem chi tiết và mở luồng chỉnh sửa nội dung tùy chỉnh ở khu vực bên dưới.</p></div><div className="rounded-2xl bg-green-50 px-4 py-3 text-sm font-bold text-green-800 dark:bg-green-500/10 dark:text-green-200">{catalog.length}/900 · {catalog.filter((item) => item.title).length}/400 Danh hiệu</div></div>
    <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-6"><input aria-label="Tìm kiếm thành tích hoặc danh hiệu" value={query} onChange={(e) => setQuery(e.target.value)} className="input mt-0 xl:col-span-2" placeholder="Tìm tên, mã hoặc mô tả..." /><select aria-label="Lọc cấp độ" value={level} onChange={(e) => setLevel(e.target.value)} className="input mt-0"><option value="all">Tất cả cấp</option>{Array.from({ length: 9 }, (_, i) => <option key={i + 1} value={i + 1}>Cấp {i + 1}</option>)}</select><select aria-label="Lọc nhóm" value={topic} onChange={(e) => setTopic(e.target.value)} className="input mt-0"><option value="all">Tất cả nhóm</option>{achievementTopics.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><select aria-label="Lọc trạng thái" value={status} onChange={(e) => setStatus(e.target.value)} className="input mt-0"><option value="all">Mọi trạng thái</option><option value="Chưa đạt">Chưa đạt</option><option value="Đã đạt">Đã đạt</option><option value="Tạm ẩn">Tạm ẩn</option></select><select aria-label="Lọc loại catalog" value={kind} onChange={(e) => setKind(e.target.value as typeof kind)} className="input mt-0"><option value="all">Thành tích & Danh hiệu</option><option value="achievement">Thành tích thường</option><option value="title">Danh hiệu</option></select></div>
    <div className="mt-3 flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-bold text-slate-500">Đang hiển thị {filtered.length} mục · Danh hiệu trong kết quả: {titles.length}</p><button type="button" className="secondary-button text-xs" onClick={reset}>Xóa bộ lọc</button></div>
    <div className="mt-4 overflow-x-auto rounded-2xl border border-red-100 dark:border-red-400/15"><table className="min-w-[980px] w-full text-left text-sm"><thead className="bg-red-50 text-xs uppercase tracking-wide text-red-800 dark:bg-red-500/10 dark:text-red-200"><tr><th className="px-4 py-3">#</th><th className="px-4 py-3">Thành tích</th><th className="px-4 py-3">Cấp</th><th className="px-4 py-3">Nhóm</th><th className="px-4 py-3">Tiến độ</th><th className="px-4 py-3">Phần thưởng</th><th className="px-4 py-3">Trạng thái</th><th className="px-4 py-3">Thao tác</th></tr></thead><tbody>{filtered.slice(0, 250).map((item) => <tr key={item.id} className="border-t border-slate-100 dark:border-white/10"><td className="px-4 py-3 font-mono text-xs">{item.rank}</td><td className="px-4 py-3"><p className="font-bold">{item.icon} {item.name}</p><p className="text-xs text-slate-500">{item.achievementCode}{item.title ? ` · ${item.title}` : ""}</p></td><td className="px-4 py-3">Cấp {item.level}</td><td className="px-4 py-3 text-xs">{item.topicLabel}</td><td className="px-4 py-3 min-w-32"><p className="text-xs font-bold">{item.currentValue}/{item.threshold} · {item.progress}%</p><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-slate-200 dark:bg-white/10"><div className="h-full rounded-full bg-green-600" style={{ width: `${item.progress}%` }} /></div></td><td className="px-4 py-3 text-xs font-semibold">+{item.rewardXp} XP{item.pieceReward ? ` · +${item.pieceReward} mảnh Cấp ${item.pieceTier}` : ""}</td><td className="px-4 py-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold dark:bg-white/10">{statusLabel(item)}</span></td><td className="px-4 py-3"><button type="button" className="secondary-button px-3 py-1.5 text-xs" onClick={() => setSelected(item)}>Xem chi tiết</button></td></tr>)}{filtered.length > 250 && <tr><td colSpan={8} className="px-4 py-3 text-center text-xs text-slate-500">Đang hiển thị 250 mục đầu để giữ bảng nhẹ; hãy dùng bộ lọc để thu hẹp catalog.</td></tr>}{filtered.length === 0 && <tr><td colSpan={8} className="px-4 py-8 text-center text-sm text-slate-500">Không tìm thấy mục phù hợp.</td></tr>}</tbody></table></div>
    <div className="mt-6 overflow-x-auto rounded-2xl border border-amber-100 dark:border-amber-400/15"><div className="border-b border-amber-100 bg-amber-50/70 px-4 py-3 dark:border-amber-400/15 dark:bg-amber-500/10"><h3 className="font-display font-bold">Bảng riêng 400 Danh hiệu</h3><p className="mt-1 text-xs text-slate-500">Danh hiệu là 400 thành tích cuối trong tổng catalog 900, không phải catalog cộng thêm.</p></div><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-white/70 text-xs uppercase tracking-wide dark:bg-white/[.03]"><tr><th className="px-4 py-3">#</th><th className="px-4 py-3">Danh hiệu</th><th className="px-4 py-3">Thành tích</th><th className="px-4 py-3">Độ khó</th><th className="px-4 py-3">Điều kiện</th><th className="px-4 py-3">Phần thưởng</th><th className="px-4 py-3">Trạng thái</th></tr></thead><tbody>{titles.slice(0, 100).map((item) => <tr key={item.id} className="border-t border-slate-100 dark:border-white/10"><td className="px-4 py-3 font-mono text-xs">{item.rank - 499}</td><td className="px-4 py-3 font-bold">{item.title}</td><td className="px-4 py-3 text-xs">{item.name}</td><td className="px-4 py-3 text-xs">{item.difficulty}</td><td className="px-4 py-3 text-xs">{item.description} · {item.currentValue}/{item.threshold}</td><td className="px-4 py-3 text-xs">+{item.rewardXp} XP · +{item.pieceReward} mảnh Cấp {item.pieceTier}{item.exchangeTicketReward ? ` · +${item.exchangeTicketReward} vé` : ""}</td><td className="px-4 py-3 text-xs font-bold">{statusLabel(item)}</td></tr>)}</tbody></table></div>
    {selected && <div className="mt-6 rounded-2xl border-2 border-green-200 bg-green-50/60 p-5 dark:border-green-400/20 dark:bg-green-500/[.06]" role="dialog" aria-label={`Chi tiết ${selected.title ?? selected.name}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-green-700 dark:text-green-300">Chi tiết công khai · {selected.achievementCode}</p><h3 className="mt-1 font-display text-2xl font-bold">{selected.title ?? selected.name}</h3></div><button type="button" className="secondary-button" onClick={() => setSelected(null)}>Đóng</button></div><div className="mt-4 grid gap-3 md:grid-cols-2"><div><p className="text-xs font-bold text-slate-500">Điều kiện & tiến độ</p><p className="mt-1 text-sm">{selected.description}</p><p className="mt-1 text-sm font-bold">{selected.currentValue}/{selected.threshold} · còn {selected.remaining} · {selected.progress}%</p></div><div><p className="text-xs font-bold text-slate-500">Ý nghĩa / cảm hứng</p><p className="mt-1 text-sm">{selected.titleMeaning ?? "Mỗi tiến bộ đều được ghi nhận trong hành trình học tập."}</p><p className="mt-1 text-xs text-slate-500">{selected.source_type === "verified" ? "Nguồn đã xác minh" : selected.source_type === "inspired" ? "Lấy cảm hứng từ" : "Không áp dụng"}: {selected.source_text ?? "Chưa có nguồn văn hóa áp dụng."}</p></div><div><p className="text-xs font-bold text-slate-500">Giải thích</p><p className="mt-1 text-sm">{selected.titleExplanation ?? selected.source_note ?? "Điều kiện và tiến độ được công khai để Ong biết cần làm gì tiếp theo."}</p></div><div><p className="text-xs font-bold text-slate-500">Phần thưởng</p><p className="mt-1 text-sm font-bold">+{selected.rewardXp} XP · +{selected.pieceReward} mảnh Cấp {selected.pieceTier}{selected.exchangeTicketReward ? ` · +${selected.exchangeTicketReward} Vé Sưu Tầm` : ""}</p></div></div></div>}
  </section>;
}
