import { useMemo, useState } from "react";
import { BatteryCharging, Brain, Coffee, Flame, Moon, Sparkles } from "lucide-react";

type Energy = "low" | "steady" | "high";
const STORAGE_KEY = "study-empire-energy-mode-v1";
const modes: Record<Energy, { label: string; detail: string; color: string; icon: typeof BatteryCharging; tasks: string[] }> = {
  low: { label: "Năng lượng thấp", detail: "Học nhẹ, ít áp lực, vẫn giữ được nhịp.", color: "bg-blue-100 text-blue-800 dark:bg-blue-400/15 dark:text-blue-200", icon: Moon, tasks: ["Ôn 5 thẻ lỗi gần nhất", "Đọc lại một khái niệm trong 10 phút", "Viết một câu phản tư sau phiên học"] },
  steady: { label: "Năng lượng ổn định", detail: "Một phiên cân bằng giữa hiểu và luyện.", color: "bg-amber-100 text-amber-800 dark:bg-amber-400/15 dark:text-amber-200", icon: Coffee, tasks: ["Làm 10 câu theo chủ đề", "Giải thích một ý bằng ngôn ngữ của mình", "Ôn lại lỗi đã đánh dấu"] },
  high: { label: "Năng lượng cao", detail: "Tận dụng đà tốt cho thử thách sâu hơn.", color: "bg-red-100 text-red-800 dark:bg-red-400/15 dark:text-red-200", icon: Flame, tasks: ["Làm một đề có giới hạn thời gian", "Tạo bộ flashcard từ bài mới", "Thử một thí nghiệm kiến thức"] },
};
export function EnergyStudyMode() {
  const [energy, setEnergy] = useState<Energy>(() => (localStorage.getItem(STORAGE_KEY) as Energy) || "steady");
  const mode = useMemo(() => modes[energy], [energy]);
  const select = (next: Energy) => { setEnergy(next); localStorage.setItem(STORAGE_KEY, next); };
  const Icon = mode.icon;
  return <section className="space-y-5" aria-labelledby="energy-mode-title"><header><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-700 dark:text-amber-300">Học theo trạng thái thật</p><h1 id="energy-mode-title" className="mt-2 font-display text-3xl font-bold">Chế độ học theo năng lượng</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Không phải ngày nào cũng cần cùng một cường độ. Chọn mức năng lượng để nhận nhiệm vụ vừa sức, không biến việc học thành cuộc đua.</p></header><section className="panel p-5"><div className="grid gap-3 md:grid-cols-3">{(Object.keys(modes) as Energy[]).map((key) => { const item = modes[key]; const ItemIcon = item.icon; return <button key={key} onClick={() => select(key)} aria-pressed={energy === key} className={`rounded-2xl border p-4 text-left transition ${energy === key ? "border-[#c62828] bg-red-50 shadow-sm dark:border-red-300 dark:bg-red-400/10" : "border-slate-100 dark:border-white/10"}`}><span className={`grid h-10 w-10 place-items-center rounded-2xl ${item.color}`}><ItemIcon className="h-5 w-5" /></span><b className="mt-3 block">{item.label}</b><span className="mt-1 block text-sm leading-5 text-slate-500">{item.detail}</span></button>; })}</div></section><section className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className={`rounded-3xl p-6 ${mode.color}`}><Icon className="h-8 w-8" /><p className="mt-5 text-xs font-bold uppercase tracking-widest opacity-70">Trạng thái đã lưu</p><h2 className="mt-2 font-display text-2xl font-bold">{mode.label}</h2><p className="mt-2 text-sm leading-6">{mode.detail}</p><div className="mt-5 flex items-center gap-2 text-sm font-semibold"><BatteryCharging className="h-4 w-4" />Gợi ý sẽ đổi theo lựa chọn này</div></div><div className="panel p-6"><div className="flex items-center gap-3"><Sparkles className="h-5 w-5 text-amber-500" /><div><h2 className="font-display text-xl font-bold">Nhiệm vụ đề xuất</h2><p className="text-xs text-slate-500">Chọn một nhiệm vụ, không cần hoàn thành tất cả.</p></div></div><div className="mt-5 grid gap-3">{mode.tasks.map((task, index) => <button key={task} className="flex items-center gap-3 rounded-2xl border border-slate-100 p-4 text-left transition hover:border-emerald-300 hover:bg-emerald-50/50 dark:border-white/10 dark:hover:bg-emerald-400/10"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-emerald-100 text-sm font-black text-emerald-700 dark:bg-emerald-400/15 dark:text-emerald-200">{index + 1}</span><span className="font-semibold">{task}</span><Brain className="ml-auto h-4 w-4 text-slate-400" /></button>)}</div></div></section></section>;
}
